# Generated by Django 4.0.1 on 2022-06-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Región')),
                ('nom_region', models.CharField(max_length=40, verbose_name='Nombre Región')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('nom_usuario', models.CharField(max_length=24, verbose_name='Nombre de Usuario')),
                ('ape_usuario', models.CharField(max_length=24, verbose_name='Apellido de Usuario')),
                ('email_usuario', models.EmailField(max_length=32, verbose_name='Email de Usuario')),
                ('contra_usuario', models.CharField(max_length=16, verbose_name='Contraseña de Usuario')),
                ('rol_usuario', models.CharField(choices=[('adm', 'Admin'), ('usr', 'Usuario'), ('usc', 'Socio')], max_length=3, verbose_name='Rol de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
    ]
